export type GoldJacketCandidate = {
  key: string;
  name: string;
  position: string;
  wikipediaTitle: string;
  isProFootballHallOfFamer: true;
  hofClass?: number;
};

const player = (
  key: string,
  name: string,
  position: string,
  wikipediaTitle = name,
  hofClass?: number,
): GoldJacketCandidate => ({
  key,
  name,
  position,
  wikipediaTitle,
  isProFootballHallOfFamer: true,
  ...(hofClass ? { hofClass } : {}),
});

export const GOLD_JACKET_PLAYERS: Record<string, GoldJacketCandidate> = {
  'adam-vinatieri': player('adam-vinatieri', 'Adam Vinatieri', 'K', 'Adam Vinatieri', 2026),
  'aeneas-williams': player('aeneas-williams', 'Aeneas Williams', 'CB'),
  'alan-page': player('alan-page', 'Alan Page', 'DT'),
  'alex-karras': player('alex-karras', 'Alex Karras', 'DT'),
  'andre-johnson': player('andre-johnson', 'Andre Johnson', 'WR', 'Andre Johnson', 2024),
  'andre-reed': player('andre-reed', 'Andre Reed', 'WR'),
  'andre-tippett': player('andre-tippett', 'Andre Tippett', 'LB'),
  'anthony-munoz': player('anthony-munoz', 'Anthony Muñoz', 'OT', 'Anthony Muñoz'),
  'antonio-gates': player('antonio-gates', 'Antonio Gates', 'TE', 'Antonio Gates', 2025),
  'art-monk': player('art-monk', 'Art Monk', 'WR'),
  'barry-sanders': player('barry-sanders', 'Barry Sanders', 'RB'),
  'bart-starr': player('bart-starr', 'Bart Starr', 'QB'),
  'bob-griese': player('bob-griese', 'Bob Griese', 'QB'),
  'bob-lilly': player('bob-lilly', 'Bob Lilly', 'DT'),
  'bobby-bell': player('bobby-bell', 'Bobby Bell', 'LB'),
  'brett-favre': player('brett-favre', 'Brett Favre', 'QB'),
  'brian-dawkins': player('brian-dawkins', 'Brian Dawkins', 'S'),
  'brian-urlacher': player('brian-urlacher', 'Brian Urlacher', 'LB'),
  'bruce-matthews': player('bruce-matthews', 'Bruce Matthews', 'OL'),
  'bruce-smith': player('bruce-smith', 'Bruce Smith', 'DE'),
  'bryant-young': player('bryant-young', 'Bryant Young', 'DT'),
  'calvin-johnson': player('calvin-johnson', 'Calvin Johnson', 'WR'),
  'carl-eller': player('carl-eller', 'Carl Eller', 'DE'),
  'champ-bailey': player('champ-bailey', 'Champ Bailey', 'CB'),
  'charles-woodson': player('charles-woodson', 'Charles Woodson', 'CB'),
  'charley-taylor': player('charley-taylor', 'Charley Taylor', 'WR'),
  'charlie-joiner': player('charlie-joiner', 'Charlie Joiner', 'WR'),
  'chuck-bednarik': player('chuck-bednarik', 'Chuck Bednarik', 'C/LB'),
  'claude-humphrey': player('claude-humphrey', 'Claude Humphrey', 'DE'),
  'cortez-kennedy': player('cortez-kennedy', 'Cortez Kennedy', 'DT'),
  'cris-carter': player('cris-carter', 'Cris Carter', 'WR'),
  'curtis-martin': player('curtis-martin', 'Curtis Martin', 'RB'),
  'dan-dierdorf': player('dan-dierdorf', 'Dan Dierdorf', 'OT'),
  'dan-fouts': player('dan-fouts', 'Dan Fouts', 'QB'),
  'dan-marino': player('dan-marino', 'Dan Marino', 'QB'),
  'darrell-green': player('darrell-green', 'Darrell Green', 'CB'),
  'darrelle-revis': player('darrelle-revis', 'Darrelle Revis', 'CB', 'Darrelle Revis', 2023),
  'deacon-jones': player('deacon-jones', 'Deacon Jones', 'DE'),
  'deion-sanders': player('deion-sanders', 'Deion Sanders', 'CB'),
  'derrick-brooks': player('derrick-brooks', 'Derrick Brooks', 'LB'),
  'derrick-thomas': player('derrick-thomas', 'Derrick Thomas', 'LB'),
  'devin-hester': player('devin-hester', 'Devin Hester', 'WR/KR', 'Devin Hester', 2024),
  'dick-butkus': player('dick-butkus', 'Dick Butkus', 'LB'),
  'night-train-lane': player('night-train-lane', "Dick 'Night Train' Lane", 'CB', 'Night Train Lane'),
  'doak-walker': player('doak-walker', 'Doak Walker', 'RB'),
  'don-maynard': player('don-maynard', 'Don Maynard', 'WR'),
  'drew-brees': player('drew-brees', 'Drew Brees', 'QB', 'Drew Brees', 2026),
  'dwight-freeney': player('dwight-freeney', 'Dwight Freeney', 'DE', 'Dwight Freeney', 2024),
  'dwight-stephenson': player('dwight-stephenson', 'Dwight Stephenson', 'C'),
  'earl-campbell': player('earl-campbell', 'Earl Campbell', 'RB'),
  'ed-reed': player('ed-reed', 'Ed Reed', 'S'),
  'edgerrin-james': player('edgerrin-james', 'Edgerrin James', 'RB'),
  'elvin-bethea': player('elvin-bethea', 'Elvin Bethea', 'DE'),
  'emlen-tunnell': player('emlen-tunnell', 'Emlen Tunnell', 'S'),
  'emmitt-smith': player('emmitt-smith', 'Emmitt Smith', 'RB'),
  'emmitt-thomas': player('emmitt-thomas', 'Emmitt Thomas', 'CB'),
  'eric-allen': player('eric-allen', 'Eric Allen', 'CB', 'Eric Allen (American football)', 2025),
  'eric-dickerson': player('eric-dickerson', 'Eric Dickerson', 'RB'),
  'fran-tarkenton': player('fran-tarkenton', 'Fran Tarkenton', 'QB'),
  'franco-harris': player('franco-harris', 'Franco Harris', 'RB'),
  'frank-gifford': player('frank-gifford', 'Frank Gifford', 'HB/WR'),
  'fred-biletnikoff': player('fred-biletnikoff', 'Fred Biletnikoff', 'WR'),
  'gale-sayers': player('gale-sayers', 'Gale Sayers', 'RB'),
  'gene-upshaw': player('gene-upshaw', 'Gene Upshaw', 'G'),
  'george-blanda': player('george-blanda', 'George Blanda', 'QB/K'),
  'harold-carmichael': player('harold-carmichael', 'Harold Carmichael', 'WR'),
  'harry-carson': player('harry-carson', 'Harry Carson', 'LB'),
  'howie-long': player('howie-long', 'Howie Long', 'DE'),
  'isaac-bruce': player('isaac-bruce', 'Isaac Bruce', 'WR'),
  'jack-lambert': player('jack-lambert', 'Jack Lambert', 'LB', 'Jack Lambert (American football)'),
  'james-lofton': player('james-lofton', 'James Lofton', 'WR'),
  'jared-allen': player('jared-allen', 'Jared Allen', 'DE', 'Jared Allen', 2025),
  'jason-taylor': player('jason-taylor', 'Jason Taylor', 'DE'),
  'jerome-bettis': player('jerome-bettis', 'Jerome Bettis', 'RB'),
  'jerry-rice': player('jerry-rice', 'Jerry Rice', 'WR'),
  'jim-brown': player('jim-brown', 'Jim Brown', 'RB'),
  'jim-kelly': player('jim-kelly', 'Jim Kelly', 'QB'),
  'joe-greene': player('joe-greene', "'Mean' Joe Greene", 'DT', 'Joe Greene'),
  'joe-montana': player('joe-montana', 'Joe Montana', 'QB'),
  'joe-namath': player('joe-namath', 'Joe Namath', 'QB'),
  'joe-schmidt': player('joe-schmidt', 'Joe Schmidt', 'LB'),
  'joe-thomas': player('joe-thomas', 'Joe Thomas', 'OT', 'Joe Thomas (offensive tackle)', 2023),
  'john-elway': player('john-elway', 'John Elway', 'QB'),
  'john-hannah': player('john-hannah', 'John Hannah', 'G'),
  'john-lynch': player('john-lynch', 'John Lynch', 'S'),
  'john-randle': player('john-randle', 'John Randle', 'DT'),
  'john-riggins': player('john-riggins', 'John Riggins', 'RB'),
  'jonathan-ogden': player('jonathan-ogden', 'Jonathan Ogden', 'OT'),
  'junior-seau': player('junior-seau', 'Junior Seau', 'LB'),
  'julius-peppers': player('julius-peppers', 'Julius Peppers', 'DE', 'Julius Peppers', 2024),
  'kellen-winslow': player('kellen-winslow', 'Kellen Winslow', 'TE', 'Kellen Winslow'),
  'ken-houston': player('ken-houston', 'Ken Houston', 'S'),
  'ken-riley': player('ken-riley', 'Ken Riley', 'CB', 'Ken Riley', 2023),
  'ken-stabler': player('ken-stabler', 'Ken Stabler', 'QB'),
  'kenny-easley': player('kenny-easley', 'Kenny Easley', 'S'),
  'kurt-warner': player('kurt-warner', 'Kurt Warner', 'QB'),
  'ladainian-tomlinson': player('ladainian-tomlinson', 'LaDainian Tomlinson', 'RB'),
  'lance-alworth': player('lance-alworth', 'Lance Alworth', 'WR'),
  'larry-csonka': player('larry-csonka', 'Larry Csonka', 'FB'),
  'larry-fitzgerald': player('larry-fitzgerald', 'Larry Fitzgerald', 'WR', 'Larry Fitzgerald', 2026),
  'larry-wilson': player('larry-wilson', 'Larry Wilson', 'S'),
  'lawrence-taylor': player('lawrence-taylor', 'Lawrence Taylor', 'LB'),
  'lee-roy-selmon': player('lee-roy-selmon', 'Lee Roy Selmon', 'DE'),
  'lem-barney': player('lem-barney', 'Lem Barney', 'CB'),
  'len-dawson': player('len-dawson', 'Len Dawson', 'QB'),
  'leroy-kelly': player('leroy-kelly', 'Leroy Kelly', 'RB'),
  'lou-groza': player('lou-groza', 'Lou Groza', 'OT/K'),
  'luke-kuechly': player('luke-kuechly', 'Luke Kuechly', 'LB', 'Luke Kuechly', 2026),
  'marcus-allen': player('marcus-allen', 'Marcus Allen', 'RB'),
  'marshall-faulk': player('marshall-faulk', 'Marshall Faulk', 'RB'),
  'marvin-harrison': player('marvin-harrison', 'Marvin Harrison', 'WR'),
  'mel-hein': player('mel-hein', 'Mel Hein', 'C/LB'),
  'merlin-olsen': player('merlin-olsen', 'Merlin Olsen', 'DT'),
  'michael-irvin': player('michael-irvin', 'Michael Irvin', 'WR'),
  'michael-strahan': player('michael-strahan', 'Michael Strahan', 'DE'),
  'mike-munchak': player('mike-munchak', 'Mike Munchak', 'G'),
  'mike-singletary': player('mike-singletary', 'Mike Singletary', 'LB'),
  'morten-andersen': player('morten-andersen', 'Morten Andersen', 'K'),
  'orlando-pace': player('orlando-pace', 'Orlando Pace', 'OT'),
  'otto-graham': player('otto-graham', 'Otto Graham', 'QB'),
  'ozzie-newsome': player('ozzie-newsome', 'Ozzie Newsome', 'TE'),
  'patrick-willis': player('patrick-willis', 'Patrick Willis', 'LB', 'Patrick Willis', 2024),
  'paul-hornung': player('paul-hornung', 'Paul Hornung', 'HB'),
  'paul-warfield': player('paul-warfield', 'Paul Warfield', 'WR'),
  'peyton-manning': player('peyton-manning', 'Peyton Manning', 'QB'),
  'randy-gradishar': player('randy-gradishar', 'Randy Gradishar', 'LB', 'Randy Gradishar', 2024),
  'randy-moss': player('randy-moss', 'Randy Moss', 'WR'),
  'randy-white': player('randy-white', 'Randy White', 'DT'),
  'ray-lewis': player('ray-lewis', 'Ray Lewis', 'LB'),
  'ray-nitschke': player('ray-nitschke', 'Ray Nitschke', 'LB'),
  'raymond-berry': player('raymond-berry', 'Raymond Berry', 'WR'),
  'reggie-white': player('reggie-white', 'Reggie White', 'DE'),
  'richard-dent': player('richard-dent', 'Richard Dent', 'DE'),
  'richard-seymour': player('richard-seymour', 'Richard Seymour', 'DE'),
  'rickey-jackson': player('rickey-jackson', 'Rickey Jackson', 'LB'),
  'rod-woodson': player('rod-woodson', 'Rod Woodson', 'DB'),
  'ronnie-lott': player('ronnie-lott', 'Ronnie Lott', 'S'),
  'ronde-barber': player('ronde-barber', 'Rondé Barber', 'CB', 'Ronde Barber', 2023),
  'roger-craig': player('roger-craig', 'Roger Craig', 'RB', 'Roger Craig (American football)', 2026),
  'roger-staubach': player('roger-staubach', 'Roger Staubach', 'QB'),
  'sam-huff': player('sam-huff', 'Sam Huff', 'LB'),
  'sam-mills': player('sam-mills', 'Sam Mills', 'LB'),
  'sammy-baugh': player('sammy-baugh', 'Sammy Baugh', 'QB'),
  'shannon-sharpe': player('shannon-sharpe', 'Shannon Sharpe', 'TE'),
  'sonny-jurgensen': player('sonny-jurgensen', 'Sonny Jurgensen', 'QB'),
  'steve-atwater': player('steve-atwater', 'Steve Atwater', 'S'),
  'steve-largent': player('steve-largent', 'Steve Largent', 'WR'),
  'steve-van-buren': player('steve-van-buren', 'Steve Van Buren', 'RB'),
  'steve-young': player('steve-young', 'Steve Young', 'QB'),
  'sterling-sharpe': player('sterling-sharpe', 'Sterling Sharpe', 'WR', 'Sterling Sharpe', 2025),
  'terrell-davis': player('terrell-davis', 'Terrell Davis', 'RB'),
  'terrell-owens': player('terrell-owens', 'Terrell Owens', 'WR'),
  'terry-bradshaw': player('terry-bradshaw', 'Terry Bradshaw', 'QB'),
  'thurman-thomas': player('thurman-thomas', 'Thurman Thomas', 'RB'),
  'tim-brown': player('tim-brown', 'Tim Brown', 'WR'),
  'tony-boselli': player('tony-boselli', 'Tony Boselli', 'OT'),
  'tony-gonzalez': player('tony-gonzalez', 'Tony Gonzalez', 'TE'),
  'troy-aikman': player('troy-aikman', 'Troy Aikman', 'QB'),
  'troy-polamalu': player('troy-polamalu', 'Troy Polamalu', 'S'),
  'ty-law': player('ty-law', 'Ty Law', 'CB'),
  'walter-jones': player('walter-jones', 'Walter Jones', 'OT'),
  'walter-payton': player('walter-payton', 'Walter Payton', 'RB'),
  'warren-moon': player('warren-moon', 'Warren Moon', 'QB'),
  'warren-sapp': player('warren-sapp', 'Warren Sapp', 'DT'),
  'willie-lanier': player('willie-lanier', 'Willie Lanier', 'LB'),
  'willie-roaf': player('willie-roaf', 'Willie Roaf', 'OT'),
  'zach-thomas': player('zach-thomas', 'Zach Thomas', 'LB', 'Zach Thomas', 2023),
};

export const GOLD_JACKET_TEAM_CANDIDATES: Record<string, string[]> = {
  cardinals: ['larry-fitzgerald', 'larry-wilson', 'aeneas-williams', 'kurt-warner', 'dan-dierdorf', 'edgerrin-james', 'emmitt-smith'],
  falcons: ['deion-sanders', 'claude-humphrey', 'morten-andersen', 'tony-gonzalez', 'dwight-freeney', 'devin-hester', 'brett-favre'],
  ravens: ['ray-lewis', 'ed-reed', 'jonathan-ogden', 'shannon-sharpe', 'rod-woodson', 'deion-sanders'],
  bills: ['jim-kelly', 'bruce-smith', 'thurman-thomas', 'andre-reed', 'james-lofton', 'terrell-owens'],
  panthers: ['luke-kuechly', 'julius-peppers', 'sam-mills', 'kevin-greene', 'jared-allen'],
  bears: ['walter-payton', 'dick-butkus', 'gale-sayers', 'brian-urlacher', 'mike-singletary', 'richard-dent', 'julius-peppers'],
  bengals: ['anthony-munoz', 'ken-riley', 'charlie-joiner', 'terrell-owens'],
  browns: ['jim-brown', 'otto-graham', 'lou-groza', 'ozzie-newsome', 'joe-thomas', 'paul-warfield', 'leroy-kelly'],
  cowboys: ['roger-staubach', 'emmitt-smith', 'bob-lilly', 'troy-aikman', 'randy-white', 'michael-irvin', 'deion-sanders'],
  broncos: ['john-elway', 'terrell-davis', 'champ-bailey', 'shannon-sharpe', 'steve-atwater', 'randy-gradishar', 'peyton-manning'],
  lions: ['barry-sanders', 'calvin-johnson', 'joe-schmidt', 'night-train-lane', 'lem-barney', 'alex-karras', 'doak-walker'],
  packers: ['bart-starr', 'brett-favre', 'reggie-white', 'ray-nitschke', 'paul-hornung', 'james-lofton', 'sterling-sharpe', 'charles-woodson'],
  texans: ['andre-johnson', 'ed-reed', 'tony-boselli'],
  colts: ['peyton-manning', 'johnny-unitas', 'marvin-harrison', 'raymond-berry', 'edgerrin-james', 'dwight-freeney', 'adam-vinatieri'],
  jaguars: ['tony-boselli'],
  chiefs: ['len-dawson', 'derrick-thomas', 'tony-gonzalez', 'willie-lanier', 'bobby-bell', 'emmitt-thomas', 'marcus-allen'],
  raiders: ['ken-stabler', 'marcus-allen', 'tim-brown', 'gene-upshaw', 'fred-biletnikoff', 'howie-long', 'charles-woodson'],
  chargers: ['ladainian-tomlinson', 'junior-seau', 'dan-fouts', 'lance-alworth', 'antonio-gates', 'kellen-winslow', 'charlie-joiner'],
  rams: ['deacon-jones', 'eric-dickerson', 'merlin-olsen', 'marshall-faulk', 'isaac-bruce', 'kurt-warner', 'orlando-pace'],
  dolphins: ['dan-marino', 'larry-csonka', 'bob-griese', 'jason-taylor', 'zach-thomas', 'paul-warfield', 'dwight-stephenson'],
  vikings: ['randy-moss', 'fran-tarkenton', 'alan-page', 'cris-carter', 'john-randle', 'carl-eller', 'jared-allen'],
  patriots: ['ty-law', 'adam-vinatieri', 'john-hannah', 'richard-seymour', 'andre-tippett', 'curtis-martin', 'randy-moss', 'junior-seau'],
  saints: ['drew-brees', 'rickey-jackson', 'willie-roaf', 'sam-mills', 'morten-andersen'],
  giants: ['lawrence-taylor', 'michael-strahan', 'frank-gifford', 'emlen-tunnell', 'harry-carson', 'sam-huff', 'mel-hein'],
  jets: ['joe-namath', 'darrelle-revis', 'curtis-martin', 'don-maynard', 'ronnie-lott', 'brett-favre', 'ed-reed'],
  eagles: ['chuck-bednarik', 'brian-dawkins', 'reggie-white', 'steve-van-buren', 'harold-carmichael', 'eric-allen', 'terrell-owens'],
  steelers: ['joe-greene', 'terry-bradshaw', 'franco-harris', 'jack-lambert', 'troy-polamalu', 'jerome-bettis', 'rod-woodson'],
  '49ers': ['jerry-rice', 'joe-montana', 'ronnie-lott', 'steve-young', 'patrick-willis', 'terrell-owens', 'roger-craig', 'deion-sanders'],
  seahawks: ['steve-largent', 'walter-jones', 'cortez-kennedy', 'kenny-easley', 'jerry-rice', 'franco-harris', 'edgerrin-james'],
  buccaneers: ['derrick-brooks', 'lee-roy-selmon', 'ronde-barber', 'warren-sapp', 'john-lynch', 'darrelle-revis', 'steve-young'],
  titans: ['earl-campbell', 'warren-moon', 'bruce-matthews', 'mike-munchak', 'elvin-bethea', 'ken-houston', 'george-blanda', 'randy-moss'],
  commanders: ['darrell-green', 'sammy-baugh', 'art-monk', 'john-riggins', 'sonny-jurgensen', 'charley-taylor', 'champ-bailey', 'deion-sanders'],
};

// Canonical Hall of Famers referenced by the team catalog but defined separately
// to keep the main object easy to scan.
GOLD_JACKET_PLAYERS['kevin-greene'] = player('kevin-greene', 'Kevin Greene', 'LB');
GOLD_JACKET_PLAYERS['johnny-unitas'] = player('johnny-unitas', 'Johnny Unitas', 'QB');

export function getGoldJacketCandidateByKey(candidateKey: string | null | undefined) {
  if (!candidateKey) return null;
  return GOLD_JACKET_PLAYERS[candidateKey] ?? null;
}

export function getTeamGoldJacketCandidates(teamSlug: string | null | undefined) {
  if (!teamSlug) return [];
  return (GOLD_JACKET_TEAM_CANDIDATES[teamSlug] ?? [])
    .map((candidateKey) => GOLD_JACKET_PLAYERS[candidateKey])
    .filter((candidate): candidate is GoldJacketCandidate => Boolean(candidate));
}

export function getGoldJacketCandidate(
  teamSlug: string | null | undefined,
  candidateKey: string | null | undefined,
) {
  if (!teamSlug || !candidateKey) return null;
  const candidateKeys = GOLD_JACKET_TEAM_CANDIDATES[teamSlug] ?? [];
  if (!candidateKeys.includes(candidateKey)) return null;
  return GOLD_JACKET_PLAYERS[candidateKey] ?? null;
}
