export type GoldJacketHeadshotRecord = {
  url: string;
  source: "nfl" | "espn";
  profileUrl: string;
};

// AUTO-GENERATED by scripts/fetch-gold-jacket-headshots.ts.
// Only exact player matches from official NFL profile headshots or strict ESPN NFL headshots are allowed.
export const GOLD_JACKET_HEADSHOTS: Record<string, GoldJacketHeadshotRecord> = {
  "adam-vinatieri": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/imfj1hl4kob4jof8hcwa",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/adam-vinatieri/"
  },
  "aeneas-williams": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lb0rdmwckvdrjvm7w5ix",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/aeneas-williams/"
  },
  "alan-page": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/qfuoxs6wh2fcz9jmd2t9",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/alan-page/"
  },
  "alex-karras": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/atlyjjglm8whgi8tiq9y",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/alex-karras/"
  },
  "andre-johnson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/iavrftkbpw4bekzl7zfv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/andre-johnson/"
  },
  "andre-reed": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/dvoxixlob0avjbmgmazk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/andre-reed/"
  },
  "andre-tippett": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zcovthmmsi7sahgvxnq8",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/andre-tippett/"
  },
  "anthony-munoz": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gxq4pfj2dmx0xp66te4j",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/anthony-munoz/"
  },
  "antonio-gates": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/kndulvysinvn4tpvt0bc",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/antonio-gates/"
  },
  "art-monk": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lhnetc7kndqwtytjysi3",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/art-monk/"
  },
  "barry-sanders": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pj2ldftirqvwh3c9pljr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/barry-sanders/"
  },
  "bart-starr": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hstldooxal3emktovptz",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bart-starr/"
  },
  "bob-griese": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ganvnmltnuhgmnmdhed5",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bob-griese/"
  },
  "bob-lilly": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/oexuhjy7i4uiaewlkn4p",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bob-lilly/"
  },
  "bobby-bell": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/w0b7zeus969ljhh1hqoo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bobby-bell/"
  },
  "brett-favre": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/m3sggjgdqlp4jqpxktvr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/brett-favre/"
  },
  "brian-dawkins": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/uer4z98pum4pancbyvnw",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/brian-dawkins/"
  },
  "brian-urlacher": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/grv500cwcjiqengfgrw1",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/brian-urlacher/"
  },
  "bruce-matthews": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lwpxlqinrbtgchvk8uvb",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bruce-matthews/"
  },
  "bruce-smith": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/z1isuze9urlmeriqctgo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bruce-smith/"
  },
  "bryant-young": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fkubylbr94xqvbzfczhx",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/bryant-young/"
  },
  "calvin-johnson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/z6dxib9sientn4m9cljh",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/calvin-johnson/"
  },
  "carl-eller": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/na8f3ix0kqx5cf3rfq5q",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/carl-eller/"
  },
  "champ-bailey": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/nxtpe8xo54kxbkyabih6",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/champ-bailey/"
  },
  "charles-woodson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gohbupnj3mhletq96zzu",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/charles-woodson/"
  },
  "charley-taylor": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ii7rywjrtsizqsmm5nqu",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/charley-taylor/"
  },
  "charlie-joiner": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rvnwuud1omemquowcor7",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/charlie-joiner/"
  },
  "chuck-bednarik": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pvotya8gt66ttrf5zsdb",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/chuck-bednarik/"
  },
  "claude-humphrey": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/aua8wjgrmqalkqwvupeb",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/claude-humphrey/"
  },
  "cortez-kennedy": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pvge87lv7e5y1rcupvsv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/cortez-kennedy/"
  },
  "cris-carter": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tb52fk83tmdpmbzwliuk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/cris-carter/"
  },
  "curtis-martin": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ikb6en50ga5g4wc8oekd",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/curtis-martin/"
  },
  "dan-dierdorf": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/uuub7jyggjqvsvz3i5ka",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dan-dierdorf/"
  },
  "dan-fouts": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/jubsyezxh2cl5gzo4dow",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dan-fouts/"
  },
  "dan-marino": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/jk97vzadmthvdyu8mbr2",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dan-marino/"
  },
  "darrell-green": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/cwcts1c4ok7r03ssniua",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/darrell-green/"
  },
  "darrelle-revis": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/claknlaznleg3wcrdfig",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/darrelle-revis/"
  },
  "deacon-jones": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/cfh2fb47ajwczu6rwtpx",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/deacon-jones/"
  },
  "deion-sanders": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hgcom8m5korxg0lvnxhj",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/deion-sanders/"
  },
  "derrick-brooks": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/z58atlnvyqyfobqrv1ca",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/derrick-brooks/"
  },
  "derrick-thomas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hc6lml7eziwksy7ng5ot",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/derrick-thomas/"
  },
  "dick-butkus": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/abdhqppmppbpdmhn0dty",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dick-butkus/"
  },
  "doak-walker": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/x4vjiwrcd6noqnnixysf",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/doak-walker/"
  },
  "don-maynard": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/s6nh537r19nluxmpvmyr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/don-maynard/"
  },
  "drew-brees": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/bt6nv11jgsirnuymookt",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/drew-brees/"
  },
  "dwight-freeney": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tk45swjxoh8bbjs50s7a",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dwight-freeney/"
  },
  "dwight-stephenson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/stkoqlkkn6wirfbrfzcv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/dwight-stephenson/"
  },
  "earl-campbell": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/svozyfy3gco5j6seywed",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/earl-campbell/"
  },
  "ed-reed": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tag3f0fdrvjp14kl9t6m",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ed-reed/"
  },
  "edgerrin-james": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/g7i6v01dasbvebawxwdm",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/edgerrin-james/"
  },
  "elvin-bethea": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ztbyqbmttw7svf0lorum",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/elvin-bethea/"
  },
  "emlen-tunnell": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gg3rzk0cvhfyakus8v8y",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/emlen-tunnell/"
  },
  "emmitt-smith": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ub78gyoyi3x1wlaow49n",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/emmitt-smith/"
  },
  "emmitt-thomas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rsl3sk7d2h8a5qduozab",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/emmitt-thomas/"
  },
  "eric-allen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/oqz1nvdgdybojfpjpsrf",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/eric-allen/"
  },
  "eric-dickerson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/jhnq2bvn8ryvxiwlfhk8",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/eric-dickerson/"
  },
  "fran-tarkenton": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ihf6rynix853sp4e3sjp",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/fran-tarkenton/"
  },
  "franco-harris": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ajagqtwni1q9a0lcbzwq",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/franco-harris/"
  },
  "frank-gifford": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/x0thvolbbc8apebrjmmr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/frank-gifford/"
  },
  "fred-biletnikoff": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/twxofug0tyee97sp00vo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/fred-biletnikoff/"
  },
  "gale-sayers": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/knt6fksmz05xswwgdncm",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/gale-sayers/"
  },
  "gene-upshaw": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/klee6wrsaudhkonpaj9j",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/gene-upshaw/"
  },
  "george-blanda": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/aofp1gfh2uwiundjxs4h",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/george-blanda/"
  },
  "harold-carmichael": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wefoaneozr3aqjxdl6ix",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/harold-carmichael/"
  },
  "harry-carson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pwg5h5pd6vfhmqqqizvz",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/harry-carson/"
  },
  "howie-long": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/l2tzxwytpvg4zllxme4y",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/howie-long/"
  },
  "isaac-bruce": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/txgl2lvmyu3m28cltnib",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/isaac-bruce/"
  },
  "jack-lambert": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/vvtzut8dhtj3e4edj5a0",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jack-lambert/"
  },
  "james-lofton": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ligcazckfbdlmcd2ekqv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/james-lofton/"
  },
  "jared-allen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/kvicq39281koeupyxqvz",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jared-allen/"
  },
  "jason-taylor": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/uemgrwzlq4210btlmcqw",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jason-taylor/"
  },
  "jerome-bettis": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zqdmcbadbq7eo8tvjwas",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jerome-bettis/"
  },
  "jerry-rice": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/g1vjcnbryx3nmg0ppsnl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jerry-rice/"
  },
  "jim-brown": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/putro8sfykabuanlfcu1",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jim-brown/"
  },
  "jim-kelly": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ezhzfqgz0wubbwdmyxlt",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jim-kelly/"
  },
  "joe-greene": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/o2d17czw2re05xp4b3wj",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/joe-greene/"
  },
  "joe-montana": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ueq3x4ldeixk2h5wq3n7",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/joe-montana/"
  },
  "joe-namath": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ssg1rcnvw9sdqcr6wz2f",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/joe-namath/"
  },
  "joe-schmidt": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ncpdhjvxeosbsgbmtnau",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/joe-schmidt/"
  },
  "joe-thomas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ojdlnhgj7zlucpucacrq",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/joe-thomas/"
  },
  "john-elway": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/qt8ysjlaemnfczfe9ffl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/john-elway/"
  },
  "john-hannah": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ebc8zlctxozwriiwemda",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/john-hannah/"
  },
  "john-lynch": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tgg0nlydguicwcylutpy",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/john-lynch/"
  },
  "john-randle": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/uterr5rjj2hwe4awl42s",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/john-randle/"
  },
  "john-riggins": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wehkyczr6mbhgqeeon5i",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/john-riggins/"
  },
  "johnny-unitas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ryyhrju5pbye3y5jm52g",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/johnny-unitas/"
  },
  "jonathan-ogden": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/nfankpq6pyoz8smsbilj",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/jonathan-ogden/"
  },
  "julius-peppers": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/c7tpbqsqzbg4vw5axw71",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/julius-peppers/"
  },
  "junior-seau": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tjckhgwowsqmlzvxebcp",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/junior-seau/"
  },
  "kellen-winslow": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pw3hoatll5kkuc9v2gva",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/kellen-winslow/"
  },
  "ken-houston": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/i1cbjgmbk3okezcqjzfr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ken-houston/"
  },
  "ken-riley": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/cthqmuyievwex8qtt7fs",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ken-riley/"
  },
  "ken-stabler": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/anwcmgpsprhjrkrwwklo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ken-stabler/"
  },
  "kenny-easley": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/acj2ycvkxytlvzjdjucv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/kenny-easley/"
  },
  "kevin-greene": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/xr1kgux2gm9pna5orpku",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/kevin-greene/"
  },
  "kurt-warner": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/xlgzhoozvi1agd8hn4kk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/kurt-warner/"
  },
  "ladainian-tomlinson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fdraejwoowicuevalpne",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ladainian-tomlinson/"
  },
  "lance-alworth": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/a1otlgdgkwqz0oprktn7",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/lance-alworth-2/"
  },
  "larry-csonka": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/xizfredzwiqcbw9vadfa",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/larry-csonka/"
  },
  "larry-fitzgerald": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/giswjsemt4f7ppwxtqgp",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/larry-fitzgerald/"
  },
  "larry-wilson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hbcedrqxwxbvaealypk0",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/larry-wilson/"
  },
  "lawrence-taylor": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/iecfuykbns6xh1znmd9c",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/lawrence-taylor/"
  },
  "lee-roy-selmon": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wkbsaelqyvvqjny5xknk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/lee-roy-selmon/"
  },
  "lem-barney": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/unb7p9ammpwhdtif5ifm",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/lem-barney/"
  },
  "len-dawson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wjhfcfla4n2g59oax8od",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/len-dawson/"
  },
  "leroy-kelly": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/vazgeyqy3obwg2gqgmbj",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/leroy-kelly/"
  },
  "lou-groza": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/i5qjaiawyxff7aq0yxzo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/lou-groza/"
  },
  "luke-kuechly": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/kx6uikwldq8afpu0bomm",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/luke-kuechly/"
  },
  "marcus-allen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wy664ewj5sglsncnjakr",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/marcus-allen/"
  },
  "marshall-faulk": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ker7p0exticomqhcbtjt",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/marshall-faulk/"
  },
  "marvin-harrison": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fni7z2tqhhaq5kbe5a0s",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/marvin-harrison/"
  },
  "mel-hein": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/s4glpdjwhzvjp77tvivz",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/mel-hein/"
  },
  "merlin-olsen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/bx9kvq0i5ezla38ap9hl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/merlin-olsen/"
  },
  "michael-irvin": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/mlouuxe889hk8vdv1mqp",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/michael-irvin/"
  },
  "michael-strahan": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zanyv0vdsqwb6djnnz5j",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/michael-strahan/"
  },
  "mike-munchak": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/omegshmowbqrxvq7uk8f",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/mike-munchak/"
  },
  "mike-singletary": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ge7hvicgirmq04dvzm8u",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/mike-singletary/"
  },
  "morten-andersen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/nk87h6cjuij14iofd5ix",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/morten-andersen/"
  },
  "night-train-lane": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/slazf2uydm3am5hfyztv",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/night-train-lane/"
  },
  "orlando-pace": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lwndbjry5t2vtjlje2d1",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/orlando-pace/"
  },
  "otto-graham": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/l26nsleyuise6pmherrd",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/otto-graham/"
  },
  "ozzie-newsome": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/eh5h2ezne6jcjwyhcugw",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ozzie-newsome/"
  },
  "patrick-willis": {
    "url": "https://static.www.nfl.com/image/upload/t_player_profile_landscape/f_auto/league/z9z1pzm6qcukxgstmlhl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/patrick-willis/"
  },
  "paul-hornung": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ij6poqqwvlthrj04dkir",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/paul-hornung/"
  },
  "paul-warfield": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lvgy4ffhozaherng6nky",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/paul-warfield/"
  },
  "peyton-manning": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/xpcd6auodk3w0vda6jal",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/peyton-manning/"
  },
  "randy-gradishar": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/j26v365gypzpexzie5ef",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/randy-gradishar/"
  },
  "randy-moss": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/udotyrimbuirasxxkd8p",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/randy-moss/"
  },
  "randy-white": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/npald08ao6ahrj8diwhn",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/randy-white/"
  },
  "ray-lewis": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/syd5vzbllkhjuwbjuiue",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ray-lewis/"
  },
  "ray-nitschke": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/g4a3ds2su6ddaaqbbmtu",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ray-nitschke/"
  },
  "raymond-berry": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rnjuiejf98ndt24oiost",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/raymond-berry/"
  },
  "reggie-white": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/i9yigp2wryewg9noeuq9",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/reggie-white/"
  },
  "richard-dent": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/jfxk36oifu0wmpdxmxaw",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/richard-dent/"
  },
  "richard-seymour": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/wghnilvp2e4nbzhfsxpl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/richard-seymour/"
  },
  "rickey-jackson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/aajr9wcjvgd7vddezkyl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/rickey-jackson/"
  },
  "rod-woodson": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/gtytylzdeeubcmxdrapg",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/rod-woodson/"
  },
  "roger-craig": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ewrcp7dcq0xaoaecjsqk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/roger-craig/"
  },
  "roger-staubach": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/vlo98smgqsmva1c82tjl",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/roger-staubach/"
  },
  "ronde-barber": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ye1pozwxxdxdvfvtsl0z",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ronde-barber/"
  },
  "ronnie-lott": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/atxlkaso6zkduzfqa3h7",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ronnie-lott/"
  },
  "sam-huff": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/p3ncxojjjcqetzgoewij",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/sam-huff/"
  },
  "sam-mills": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/x5ayzdjsqp1zyn2pvvl1",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/sam-mills/"
  },
  "sammy-baugh": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/eida09r1zsqt4qemngmn",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/sammy-baugh/"
  },
  "shannon-sharpe": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/pl9dwxqbdarzuirkjeri",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/shannon-sharpe/"
  },
  "sonny-jurgensen": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/lchsfr6kvo3q1dpnyjes",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/sonny-jurgensen/"
  },
  "sterling-sharpe": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/bslcx5nft2cxkr4cjx9k",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/sterling-sharpe/"
  },
  "steve-atwater": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/j3xxo3zjpt29erl0wsdf",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/steve-atwater/"
  },
  "steve-largent": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/uwi8mvpiavmova7skp7q",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/steve-largent/"
  },
  "steve-van-buren": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zx28hgh2mb6axfv4fatm",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/steve-van-buren/"
  },
  "steve-young": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/kfrm5wzrogcovwymoez8",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/steve-young/"
  },
  "terrell-davis": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/smkzf1k9eeymmon7dzco",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/terrell-davis/"
  },
  "terrell-owens": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/c41avnwoegxy9nnwmgbo",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/terrell-owens/"
  },
  "terry-bradshaw": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/xmjv8lqrxaspc8joz0v4",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/terry-bradshaw/"
  },
  "thurman-thomas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/oy5j1auukzykwe8mhhhf",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/thurman-thomas/"
  },
  "tim-brown": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/qhdz2r0h4zlxxmzsgemc",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/tim-brown/"
  },
  "tony-boselli": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rofuwev687rwaavow0t5",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/tony-boselli/"
  },
  "tony-gonzalez": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/enbspvy0ahsyznomitre",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/tony-gonzalez/"
  },
  "troy-aikman": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/skagdrvhtf6ywlxwlrou",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/troy-aikman/"
  },
  "troy-polamalu": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fccuwiovxnaq9lm7y0gq",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/troy-polamalu/"
  },
  "ty-law": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/eepyfx4wk22s1kctoeqk",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/ty-law/"
  },
  "walter-jones": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/x1cyk4dzlwh0wk23iuj6",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/walter-jones/"
  },
  "walter-payton": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/yjatyzmf5yhgs0v9qcze",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/walter-payton/"
  },
  "warren-moon": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/nmnwarb1fy1d8xrefvfc",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/warren-moon/"
  },
  "warren-sapp": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/vy7oxarkyorx4f2d9w0o",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/warren-sapp/"
  },
  "willie-lanier": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hgjq9o9tspbmgw84xxyq",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/willie-lanier/"
  },
  "willie-roaf": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/vbhqmy7sz7crxafuzqkx",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/willie-roaf/"
  },
  "zach-thomas": {
    "url": "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/s4gdnfi1fdmjvqwfb8bq",
    "source": "nfl",
    "profileUrl": "https://www.nfl.com/players/zach-thomas/"
  }
};
