// @ts-nocheck
import test from "node:test";
import assert from "node:assert/strict";

import {
  GOLD_JACKET_TEAM_CANDIDATES,
} from "../lib/gold-jackets/catalog.ts";

const EXPECTED = {
  cardinals: [
    "larry-fitzgerald",
    "larry-wilson",
    "aeneas-williams",
    "kurt-warner",
    "dan-dierdorf",
    "edgerrin-james",
    "emmitt-smith",
  ],
  falcons: [
    "deion-sanders",
    "claude-humphrey",
    "morten-andersen",
    "tony-gonzalez",
    "dwight-freeney",
    "devin-hester",
    "brett-favre",
  ],
  ravens: [
    "ray-lewis",
    "ed-reed",
    "jonathan-ogden",
    "shannon-sharpe",
    "rod-woodson",
    "deion-sanders",
  ],
  bills: [
    "jim-kelly",
    "bruce-smith",
    "thurman-thomas",
    "andre-reed",
    "james-lofton",
    "terrell-owens",
  ],
  panthers: [
    "luke-kuechly",
    "julius-peppers",
    "sam-mills",
    "kevin-greene",
    "jared-allen",
  ],
  bears: [
    "walter-payton",
    "dick-butkus",
    "gale-sayers",
    "brian-urlacher",
    "mike-singletary",
    "richard-dent",
    "julius-peppers",
  ],
  bengals: [
    "anthony-munoz",
    "ken-riley",
    "charlie-joiner",
    "terrell-owens",
  ],
  browns: [
    "jim-brown",
    "otto-graham",
    "lou-groza",
    "ozzie-newsome",
    "joe-thomas",
    "paul-warfield",
    "leroy-kelly",
  ],
  cowboys: [
    "roger-staubach",
    "emmitt-smith",
    "bob-lilly",
    "troy-aikman",
    "randy-white",
    "michael-irvin",
    "deion-sanders",
  ],
  broncos: [
    "john-elway",
    "terrell-davis",
    "champ-bailey",
    "shannon-sharpe",
    "steve-atwater",
    "randy-gradishar",
    "peyton-manning",
  ],
  lions: [
    "barry-sanders",
    "calvin-johnson",
    "joe-schmidt",
    "night-train-lane",
    "lem-barney",
    "alex-karras",
    "doak-walker",
  ],
  packers: [
    "bart-starr",
    "brett-favre",
    "reggie-white",
    "ray-nitschke",
    "paul-hornung",
    "james-lofton",
    "sterling-sharpe",
    "charles-woodson",
  ],
  texans: [
    "andre-johnson",
    "ed-reed",
    "tony-boselli",
  ],
  colts: [
    "peyton-manning",
    "johnny-unitas",
    "marvin-harrison",
    "raymond-berry",
    "edgerrin-james",
    "dwight-freeney",
    "adam-vinatieri",
  ],
  jaguars: [
    "tony-boselli",
  ],
  chiefs: [
    "len-dawson",
    "derrick-thomas",
    "tony-gonzalez",
    "willie-lanier",
    "bobby-bell",
    "emmitt-thomas",
    "marcus-allen",
  ],
  raiders: [
    "ken-stabler",
    "marcus-allen",
    "tim-brown",
    "gene-upshaw",
    "fred-biletnikoff",
    "howie-long",
    "charles-woodson",
  ],
  chargers: [
    "ladainian-tomlinson",
    "junior-seau",
    "dan-fouts",
    "lance-alworth",
    "antonio-gates",
    "kellen-winslow",
    "charlie-joiner",
  ],
  rams: [
    "deacon-jones",
    "eric-dickerson",
    "merlin-olsen",
    "marshall-faulk",
    "isaac-bruce",
    "kurt-warner",
    "orlando-pace",
  ],
  dolphins: [
    "dan-marino",
    "larry-csonka",
    "bob-griese",
    "jason-taylor",
    "zach-thomas",
    "paul-warfield",
    "dwight-stephenson",
  ],
  vikings: [
    "randy-moss",
    "fran-tarkenton",
    "alan-page",
    "cris-carter",
    "john-randle",
    "carl-eller",
    "jared-allen",
  ],
  patriots: [
    "ty-law",
    "adam-vinatieri",
    "john-hannah",
    "richard-seymour",
    "andre-tippett",
    "curtis-martin",
    "randy-moss",
    "junior-seau",
  ],
  saints: [
    "drew-brees",
    "rickey-jackson",
    "willie-roaf",
    "sam-mills",
    "morten-andersen",
  ],
  giants: [
    "lawrence-taylor",
    "michael-strahan",
    "frank-gifford",
    "emlen-tunnell",
    "harry-carson",
    "sam-huff",
    "mel-hein",
  ],
  jets: [
    "joe-namath",
    "darrelle-revis",
    "curtis-martin",
    "don-maynard",
    "ronnie-lott",
    "brett-favre",
    "ed-reed",
  ],
  eagles: [
    "chuck-bednarik",
    "brian-dawkins",
    "reggie-white",
    "steve-van-buren",
    "harold-carmichael",
    "eric-allen",
    "terrell-owens",
  ],
  steelers: [
    "joe-greene",
    "terry-bradshaw",
    "franco-harris",
    "jack-lambert",
    "troy-polamalu",
    "jerome-bettis",
    "rod-woodson",
  ],
  "49ers": [
    "jerry-rice",
    "joe-montana",
    "ronnie-lott",
    "steve-young",
    "patrick-willis",
    "terrell-owens",
    "roger-craig",
    "deion-sanders",
  ],
  seahawks: [
    "steve-largent",
    "walter-jones",
    "cortez-kennedy",
    "kenny-easley",
    "jerry-rice",
    "franco-harris",
    "edgerrin-james",
  ],
  buccaneers: [
    "derrick-brooks",
    "lee-roy-selmon",
    "ronde-barber",
    "warren-sapp",
    "john-lynch",
    "darrelle-revis",
    "steve-young",
  ],
  titans: [
    "earl-campbell",
    "warren-moon",
    "bruce-matthews",
    "mike-munchak",
    "elvin-bethea",
    "ken-houston",
    "george-blanda",
    "randy-moss",
  ],
  commanders: [
    "darrell-green",
    "sammy-baugh",
    "art-monk",
    "john-riggins",
    "sonny-jurgensen",
    "charley-taylor",
    "champ-bailey",
    "deion-sanders",
  ],
};

test("all 32 Gold Jacket candidate boards use franchise-specific greatness order", () => {
  assert.deepEqual(GOLD_JACKET_TEAM_CANDIDATES, EXPECTED);
});

test("Deion Sanders is first for Atlanta but last for Dallas, San Francisco and Washington", () => {
  assert.equal(GOLD_JACKET_TEAM_CANDIDATES.falcons[0], "deion-sanders");
  assert.equal(GOLD_JACKET_TEAM_CANDIDATES.cowboys.at(-1), "deion-sanders");
  assert.equal(GOLD_JACKET_TEAM_CANDIDATES["49ers"].at(-1), "deion-sanders");
  assert.equal(GOLD_JACKET_TEAM_CANDIDATES.commanders.at(-1), "deion-sanders");
});
