import { writeFile } from "node:fs/promises";
import { GOLD_JACKET_PLAYERS } from "../lib/gold-jackets/catalog.ts";
import {
  resolveGoldJacketHeadshot,
  type GoldJacketHeadshot,
} from "../lib/gold-jackets/headshot-resolver.ts";

const OUTPUT = new URL("../lib/gold-jackets/headshot-data.ts", import.meta.url);
const CONCURRENCY = 6;
const candidates = Object.values(GOLD_JACKET_PLAYERS).sort((a, b) => a.name.localeCompare(b.name));
const resolved: Record<string, GoldJacketHeadshot> = {};
const missing: Array<{ key: string; name: string }> = [];
let cursor = 0;

async function worker() {
  while (true) {
    const index = cursor++;
    const candidate = candidates[index];
    if (!candidate) return;

    const headshot = await resolveGoldJacketHeadshot(candidate);
    if (headshot) {
      resolved[candidate.key] = headshot;
      console.log(`✓ ${candidate.name} — ${headshot.source.toUpperCase()}`);
    } else {
      missing.push({ key: candidate.key, name: candidate.name });
      console.log(`✗ ${candidate.name} — NO VERIFIED HEADSHOT`);
    }
  }
}

await Promise.all(Array.from({ length: Math.min(CONCURRENCY, candidates.length) }, () => worker()));

const ordered = Object.fromEntries(
  Object.entries(resolved).sort(([a], [b]) => a.localeCompare(b)),
);
const output = `export type GoldJacketHeadshotRecord = {\n  url: string;\n  source: "nfl" | "espn";\n  profileUrl: string;\n};\n\n// AUTO-GENERATED by scripts/fetch-gold-jacket-headshots.ts.\n// Only exact player matches from official NFL profile headshots or strict ESPN NFL headshots are allowed.\nexport const GOLD_JACKET_HEADSHOTS: Record<string, GoldJacketHeadshotRecord> = ${JSON.stringify(ordered, null, 2)};\n`;
await writeFile(OUTPUT, output, "utf8");

console.log("");
console.log("========================================");
console.log("GOLD JACKET HEADSHOT AUDIT");
console.log("========================================");
console.log(`Verified: ${Object.keys(resolved).length}/${candidates.length}`);

if (missing.length) {
  console.log("");
  console.log("Missing — these are intentionally NOT replaced with fuzzy/random photos:");
  for (const item of missing.sort((a, b) => a.name.localeCompare(b.name))) {
    console.log(`  - ${item.name} (${item.key})`);
  }
  process.exitCode = 2;
} else {
  console.log("Every Gold Jacket catalog player has a verified playing-career roster/profile headshot.");
}
