import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const workflow =
  fs.readFileSync(
    "lib/discord/trade-workflow.ts",
    "utf8",
  );

const imageRoute =
  fs.readFileSync(
    "app/api/trades/[id]/image/route.ts",
    "utf8",
  );

test(
  "Schefter sender uses Schefter bot and everyone ping",
  () => {
    assert.match(
      workflow,
      /ADAM_SCHEFTER_BOT_TOKEN/,
    );

    assert.match(
      workflow,
      /content:\s*"@everyone"/,
    );

    assert.match(
      workflow,
      /parse:\s*\[\s*"everyone"\s*,?\s*\]/,
    );
  },
);

test(
  "Schefter image is generated by native ImageResponse",
  () => {
    assert.match(
      imageRoute,
      /from\s+"next\/og"/,
    );

    assert.match(
      imageRoute,
      /new ImageResponse\s*\(/,
    );
  },
);

test(
  "Schefter card contains requested social metrics",
  () => {
    for (const marker of [
      "Trade terms, per source:",
      '"189"',
      '"913"',
      '"6K"',
      '"3.4M"',
    ]) {
      assert.ok(
        imageRoute.includes(marker),
        `missing Schefter card marker: ${marker}`,
      );
    }
  },
);

test(
  "Schefter image has no legacy headshot or Sharp dependency",
  () => {
    for (const forbidden of [
      /legacy-image/,
      /schefter-x-renderer/,
      /renderSchefterXTrade/,
      /Buffer\.from/,
      /from\s+"sharp"/,
    ]) {
      assert.doesNotMatch(
        imageRoute,
        forbidden,
      );
    }
  },
);
