create extension if not exists pgcrypto;

create table if not exists public.madden_players (
  id uuid primary key default gen_random_uuid(),
  canonical_name text not null,
  normalized_name text not null,
  primary_position text,
  baseline_team_id uuid references public.teams(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists madden_players_normalized_name_idx
  on public.madden_players (normalized_name);

create index if not exists madden_players_baseline_team_idx
  on public.madden_players (baseline_team_id);

create table if not exists public.madden_player_external_ids (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.madden_players(id) on delete cascade,
  source text not null,
  external_id text not null,
  created_at timestamptz not null default now(),
  unique (source, external_id)
);

create index if not exists madden_player_external_ids_player_idx
  on public.madden_player_external_ids (player_id);

create table if not exists public.madden_player_snapshots (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.madden_players(id) on delete cascade,
  league_id uuid references public.leagues(id) on delete cascade,
  team_id uuid references public.teams(id) on delete set null,
  source text not null,
  source_priority smallint not null default 100,
  game_version text not null,
  overall smallint check (overall between 0 and 99),
  jersey_number smallint check (jersey_number between 0 and 99),
  position text,
  archetype text,
  dev_trait text,
  attributes jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  imported_at timestamptz not null default now()
);

create index if not exists madden_player_snapshots_player_idx
  on public.madden_player_snapshots (player_id, captured_at desc);

create index if not exists madden_player_snapshots_league_idx
  on public.madden_player_snapshots (league_id, captured_at desc);

create index if not exists madden_player_snapshots_source_idx
  on public.madden_player_snapshots (source, game_version, captured_at desc);

create unique index if not exists madden_player_baseline_snapshot_unique
  on public.madden_player_snapshots (player_id, source, game_version)
  where league_id is null;

create unique index if not exists madden_player_franchise_snapshot_unique
  on public.madden_player_snapshots (player_id, source, game_version, league_id)
  where league_id is not null;

create table if not exists public.madden_team_snapshots (
  id bigint generated by default as identity primary key,
  league_id uuid references public.leagues(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  source text not null,
  source_priority smallint not null default 100,
  game_version text not null,
  overall smallint check (overall between 0 and 99),
  offense smallint check (offense between 0 and 99),
  defense smallint check (defense between 0 and 99),
  attributes jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  imported_at timestamptz not null default now()
);

create index if not exists madden_team_snapshots_team_idx
  on public.madden_team_snapshots (team_id, captured_at desc);

create unique index if not exists madden_team_baseline_snapshot_unique
  on public.madden_team_snapshots (team_id, source, game_version)
  where league_id is null;

create unique index if not exists madden_team_franchise_snapshot_unique
  on public.madden_team_snapshots (team_id, source, game_version, league_id)
  where league_id is not null;

create table if not exists public.madden_import_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  game_version text not null,
  league_id uuid references public.leagues(id) on delete set null,
  status text not null default 'running',
  player_count integer not null default 0,
  team_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

grant select on public.madden_players to anon, authenticated;
grant select on public.madden_player_external_ids to anon, authenticated;
grant select on public.madden_player_snapshots to anon, authenticated;
grant select on public.madden_team_snapshots to anon, authenticated;
grant select on public.madden_import_runs to authenticated;

grant all on public.madden_players to service_role;
grant all on public.madden_player_external_ids to service_role;
grant all on public.madden_player_snapshots to service_role;
grant all on public.madden_team_snapshots to service_role;
grant all on public.madden_import_runs to service_role;
